FROM openjdk:17-jdk-slim as build


WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

COPY src src

RUN chmod +x ./gradlew

RUN ./gradlew build

FROM openjdk:17-jdk-slim

COPY --from=build /app/build/libs/*.jar eureka-server-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/eureka-server-0.0.1-SNAPSHOT.jar"]